### ISSUE TITLE
github.com/golang/tools API change

### ISSUE THREAD

**Issue by Dr-Terrible** [mdempsky/maligned#1]
I got this compilation error while executing `go get github.com/mdempsky/maligned` with Go1.5.1:

> ./maligned.go:50: impossible type assertion:
>     *"golang.org/x/tools/go/types".Struct does not implement "go/types".Type (wrong type for Underlying method)
>         have Underlying() "golang.org/x/tools/go/types".Type
>         want Underlying() "go/types".Type

`github.com/golang/tools` introduced an API change for go/types around commit: https://github.com/golang/tools/commit/2477c0d5780ddec6439a9322a6862dfe20cc8b81.

**Comment by Dieterbe** [comment]
+1

**Comment by dgryski** [comment]
Replacing the`/x/tools/go/types` with the standard `go/types` included with 1.6 makes this build again.
