### ISSUE TITLE
port from go/loader to go/packages

### ISSUE THREAD

**Issue by mvdan** [mdempsky/maligned#16]
As [pointed out on Twitter](https://twitter.com/mvdan_/status/1321746706799742976). This would add support for modules, and also modernize the tool quite a bit as go/loader hasn't been supported in years.

When done, please update https://github.com/golang/go/issues/24661 with a comment so that the "maligned" checklist item can be ticked off.

**Comment by mdempsky** [comment]
Per feedback during tonight's Twitch stream, I updated it to use x/analysis. I think this is done now. I've checked maligned in the list and added a comment. Thanks for the suggestion!
