### ISSUE TITLE
maligned ignores custom build tags recently

### ISSUE THREAD

**Issue by itchyny** [mdempsky/maligned#18]
Since c37866e2d38b8e33600b215e4095af870becd4d8, maligned complains on duplicate methods in different custom build tags.

main.go
```go
package main

func main() {
	debug("x")
}
```
debug.go
```go
// +build debug

package main

func debug(s string) { println(s) }
```
release.go
```go
// +build !debug

package main

func debug(string) {}
```

```sh
 % maligned *.go
/tmp/release.go:5:6: debug redeclared in this block
/tmp/debug.go:5:6:      other declaration of debug
/tmp/release.go:5:6: debug redeclared in this block
/tmp/debug.go:5:6:      other declaration of debug
maligned: 4 errors during loading
```

Before c37866e2d38b8e33600b215e4095af870becd4d8, maligned worked well in this situation.

**Comment by itchyny** [comment]
The code is just a minimum reproduction, my repo includes bunch of structs that I want to check maligned.

**Comment by mdempsky** [comment]
That seems to be an artifact of switching from x/tools/go/loader to x/tools/go/packages. In general, I'd say the new behavior is more expected, and you should be running something like "maligned ." and then separately "maligned -tags=debug .". But I notice the singlechecker driver program's -help output mentions:

```
  -tags string
    	no effect (deprecated)
```

so I'm not sure how users are supposed to supply custom tags. Maybe @dmitshur has pointers here.

**Comment by dmitshur** [comment]
(For posterity, the x/tools/go/packages API supports specifying build tags via [`Config.BuildFlags`](http://pkg.go.dev/golang.org/x/tools/go/packages#Config.BuildFlags) field; this was golang/go#26509.)

I'm not closely familiar with the current state of the `singlechecker` package, but as far as I can tell it doesn't support specifying build tags via a CLI flag, and there's no [open issue](https://goissues.org/golang.org/x/tools/go/analysis/singlechecker) for it. So it would be a feature request (one that may be in scope, or possibly out of scope). Maybe @mvdan or @dominikh know more. (If it's out of scope or not going to be implemented soon, you can implement your own version of `singlechecker` to get full control over your tool's CLI.)

I can think of using the [`GOFLAGS`](https://golang.org/cmd/go/#hdr-Environment_variables) environment variable to specify build tags:

```
$ GOFLAGS='-tags=debug' maligned .
```

Which works, but I don't know if that should to be considered a recommended solution or a temporary workaround.

**Comment by itchyny** [comment]
Thank you for your comments. I understand how to correct my script so please close if there is no action to take against this issue.
