### ISSUE TITLE
Optimize for pointer slots too

### ISSUE THREAD

**Issue by mdempsky** [mdempsky/maligned#6]
When scanning objects during GC, the standard compiler/runtime only scan as far as the last pointer slot in an object.  If fields are sorted so that all of the pointer-y fields come first, then the GC may be able to short-circuit its scan work slightly.

**Comment by erwanor** [comment]
Nice, I can implement that. Would you rather leave to the user to specify which they want to prioritize (struct alignment or GC optimization) or just print both? Otherwise, what criteria to use to decide which one has the most priority?

**Comment by mdempsky** [comment]
I would probably just favor size over pointers-first. I think pointers-first is a smaller win than using less memory.

That said, off hand I can't think of any struct layouts where the two layout strategies are actually in conflict. If you have one, please share.
